apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    runAsNonRoot: true
    # run as non-root user
    runAsUser: 1500
    # run processes using this uid 
    runAsGroup: 2000
    # run processes using this gid
    fsGroup: 3000
    # group id for ownership of mounted volumes and files
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: souvikdocks250/ubuntu_wuser
    imagePullPolicy: Always
    command: [ "sh", "-c", "sleep 3600" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
      # allow running processes more privideged than their parent processes if true
      readOnlyRootFilesystem: true
      # Mounts the container's root filesystem as read-only if true
