apiVersion: v1
kind: Pod
metadata:
  name: ngx-d
  labels:
    app: ngx-d
spec:
  containers:
  - name: nginx-c
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-index-config
      mountPath: /usr/share/nginx/html/index.html
      subPath: index.html
      readOnly: true
  volumes:
  - name: nginx-index-config
    configMap:
      name: custom-index

---

apiVersion: v1
kind: Service
metadata:
  name: ngx-d-service
  labels:
    app: ngx-d
spec:
  type: LoadBalancer
  selector:
    app: ngx-d
  ports:
    - name: nginx-port
      port: 8080
      targetPort: 80

