apiVersion: v1
kind: Pod
metadata:
  name: httpd
  namespace: secops
  labels:
    app: httpd

spec:
  containers:
  - name: httpd-alpine
    image: httpd:alpine
  
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: secops                 
spec:
  type: LoadBalancer 
  selector:
    app: httpd

  ports:
    - name: httpd-port
      port: 8080
      targetPort: 80
