apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-test
  labels:
    app: multicontainer-test

spec:
  restartPolicy: OnFailure
  containers:
  - name: busybox-con
    image: busybox
    command:
      - sleep
      - "3600"

