apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
  labels:
    app: multicontainer-test

spec:
  containers:
  - name: nginx-c
    image: nginx
    ports:
    - containerPort: 80

    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: cache-volume

  initContainers:
  - name: busybox-c
    image: busybox
    command:
    - /bin/sh
    - -c
    - wget -O /work-dir/index.html http://neverssl.com/online

    volumeMounts:
    - mountPath: /work-dir
      name: cache-volume
  
  volumes:
  - name: cache-volume
    emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: multicontainer-test
spec:
  type: LoadBalancer
  selector:
    app: multicontainer-test
  ports:
    - name: nginx-port
      port: 80
      targetPort: 80

