apiVersion: v1
kind: Pod
metadata:
  name: check-logging
  labels:
    app: logging
spec:
  volumes:
    - name: shared
      emptyDir: {}
  containers:
    - name: gen-file
      image: ubuntu
      command: ["/bin/bash", "-ec"]
      args:
      - while true; do 
            date >> /var/file/log.txt; 
            sleep 5;
        done
      volumeMounts:
        - mountPath: /var/file
          name: shared
      
    - name: check-log
      image: busybox
      command: ["/bin/sh", "-ec"]
      args:
      - while true; do
            sleep 8;
            cat /var/logging/log.txt; 
        done
      volumeMounts:
        - mountPath: /var/logging
          name: shared
