apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
  labels:
    test: liveness-po

spec:
  containers:
  - name: busybox-con
    image: busybox
    command:
    - /bin/sh
    - -c
    - sleep 30; touch /tmp/debug; sleep 30; rm /tmp/debug;

    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/debug
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 2  #optional
