name: Yaml Lint Check
on: 
  pull_request:
  push:
    branches:
     - main

jobs:
  lintAllTheThings:
    name: yaml-linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: yaml-lint
      uses: ibiqlik/action-yamllint@v3

  uploadArtifact:
    needs: [lintAllTheThings]
    runs-on: ubuntu-latest
    steps:
    - name: uploading-logs
      uses: actions/upload-artifact@v2
    - run: echo ${{ steps.yaml-lint.outputs.logfile }}
      if: always()
      with:
        name: yamllint-logfile
        path: ${{ steps.yaml-lint.outputs.logfile }}
