name: Yaml Lint Check
on: 
  pull_request:
  push:
    branches:
     - main

jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            rules:
              new-line-at-end-of-file:
                level: warning
              trailing-spaces:
                level: warning
              indentation:
                level: warning
              empty-lines:
                level: warning
              line-length:
                level: warning
              brackets:
                level: warning

      - name: "Logging warnings"
        run: echo ${{ steps.yaml-lint.outputs.logfile }}

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: yamllint-logs
          path: ${{ steps.yaml-lint.outputs.logfile }}
